[package]
name = "ngram_iter"
version = "0.1.0"
edition = "2021"
authors = ["D. Scott Boggs"]
license = "LGPLv3"
description = "An iterator of arbitrary N-grams of rust Copy types"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
